SELECT
    DATE_TRUNC('day', TS) AS trade_day,
    TRADE_SURFACE,
    COUNT(*) AS trade_count,
    SUM(CONSUMER_VOLUME_USD) AS total_volume
FROM ANALYTICS.CIFER.MEASURES_CONSUMER_TRADES
WHERE TRADE_COMPLETED = 1
GROUP BY DATE_TRUNC('day', TS), TRADE_SURFACE
