name: Test Action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test SQL Audit Action
        uses: ./  # References the action in the current repo
        with:
          backend-hostname: coinbase-staging-api.singleorigin.tech
          api-key: ${{ secrets.SO_CODE_REVIEW_HOSTNAME }}
          upload-artifact: 'true'
