name: Test Action

on:
  pull_request:
  pull_request_review_comment:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          agent-api-url: ${{ secrets.SO_CODE_REVIEW_URL }} # change to actual agent api url in github secrets
          agent-api-key: ${{ secrets.SO_CODE_REVIEW_API_KEY }}
